### ISSUE TITLE
Message 'skipping incompatible' is shown when doing make

### ISSUE THREAD

**Issue by tngan** [dji-sdk/manifold_cam#1]
I've already installed ffmpeg and gstreamer, when `make` is executed, the following messages are shown:

```
gcc -O2 -o test test.c -ldcam -lpthread
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libdcam.so when searching for -ldcam
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libdcam.so when searching for -ldcam
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../libdcam.so when searching for -ldcam
/usr/bin/ld: skipping incompatible //usr/lib/libdcam.so when searching for -ldcam
/usr/bin/ld: cannot find -ldcam
```

Does libdcam.so only support 32 bit platform ?

**Comment by lanyusea** [comment]
~~1. ffmpeg and gstreamer have nothing to do with this program~~ my fault
1. please install the libdcam.so first before compilation. the readme doesn't describe it clearly
2. it only supports Manifold, which is ARM. no other platform is supported
