### ISSUE TITLE
Failed to make

### ISSUE THREAD

**Issue by younger7** [dji-sdk/manifold_cam#3]
when i tab "make" , here came the error "cannot find -ldcam". i can't solve the problem. so i need your help

**Comment by lanyusea** [comment]
please `sudo make install` first before compilation

**Comment by tngan** [comment]
It's because you have to install libdcam.so in/usr/lib.

**Comment by lanyusea** [comment]
@younger7  @tngan  

as I remember, the library has already been installed when it get out of the factory.

so I'm a little puzzled since your Manifold don't have it and you guys have to install the library manually

@_@

**Comment by tngan** [comment]
@lanyusea You are right, it's already in Manifold. I just misunderstood the use of package yesterday.

**Comment by younger7** [comment]
after "sudo make install", i try it again. here is the result:
bjly@bjly-Lenovo-K2450:~$ cd Mani
bash: cd: Mani: No such file or directory
bjly@bjly-Lenovo-K2450:~$ cd Manifold-Cam-master/
bjly@bjly-Lenovo-K2450:~/Manifold-Cam-master$ sudo make install 
[sudo] password for bjly: 
Sorry, try again.
[sudo] password for bjly: 
cp ./libdcam.so /usr/lib
bjly@bjly-Lenovo-K2450:~/Manifold-Cam-master$ make
gcc -O2 -o test test.c -L /home/bjly/Manifold-Cam-master -ldcam -lpthread
/usr/bin/ld: skipping incompatible /home/bjly/Manifold-Cam-master/libdcam.so when searching for -ldcam
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libdcam.so when searching for -ldcam
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libdcam.so when searching for -ldcam
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../libdcam.so when searching for -ldcam
/usr/bin/ld: skipping incompatible //usr/lib/libdcam.so when searching for -ldcam
/usr/bin/ld: cannot find -ldcam
collect2: error: ld returned 1 exit status
make: **\* [test] Error 1

**Comment by younger7** [comment]
it is still searching for -ldcam. why is that?

**Comment by lanyusea** [comment]
@younger7 
Please... **Manifold**, please...

---update---
updated the readme, highlighted the Manifold.
hope no more similar issue
![](http://i.imgur.com/iWKad22.jpg)
