### ISSUE TITLE
Bug in manifold_cam_init()

### ISSUE THREAD

**Issue by kc8goq** [dji-sdk/manifold_cam#4]
In our tests the test.c (and corresponding ROS package) hang at the manifold_cam_init() function call and do not proceed to the frame grabbing portions of the code.

**Comment by lanyusea** [comment]
could you specify `hang`. I don't know what's going on without a log

**Comment by kc8goq** [comment]
Sorry, was trying to report after a long day of debugging.    In both the test.c program and the dji_sdk_read_cam program when the manifold_cam_init() is called, it appears to never return a value and the program does not proceed past this line.   On the DJI GO app the camera feed is displayed each time without issues however.

What information can I provide to maximally assist you?

**Comment by lanyusea** [comment]
1. Did you run in on Manifold? I have to ask this because the last two issues happened not on Manifold  :crying_cat_face: 
2. Did you `sudo` before you run?
3. any printing in your terminal or nothing at all? there should be tons of log messages in our sample code

**Comment by kc8goq** [comment]
1. Yes, ran it on the Manifold, running the preinstalled Ubuntu 14.04 LTS.
2.  Yes, I ran sudo ./test -tg for the example program and sudo -s then roslaunch... for the ros code
3. Yes, the program puts out a great deal of items, especially as the h264 encoder is coming online.
   For debugging we added printf statements before the init() function and after to help assess the program progression.  One of my colleagues is still in the lab and can grab some data.

**Comment by lanyusea** [comment]
Then I think the program is running well.
since you use -t and DJI GO catches the video.

what makes you think it hangs?
could you see the video stream by using -d?

**Comment by kc8goq** [comment]
The issue is the frame grabber functionality, which executes after the init() function.   The program never gets there.

**Comment by lanyusea** [comment]
you mean you cannot reach anything after https://github.com/dji-sdk/Manifold-Cam/blob/master/test.c#L123 ?

**Comment by kc8goq** [comment]
Correct.  (Thanks for your help btw!)

**Comment by lanyusea** [comment]
so,what about get_images_loop(), which is in another thread?

**Comment by lanyusea** [comment]
and you can see the video by using -d on Manifold, right?

**Comment by kc8goq** [comment]
My understanding is that the threads are created after the init() function?  https://github.com/dji-sdk/Manifold-Cam/blob/master/test.c#L134

I was using ssh before, so I never tried -d.  My colleague is testing it now.

**Comment by lanyusea** [comment]
ok, then I got where goes wrong.
if you're in SSH, the xinit& won't work, which matters a graphical library this package needs

check the readme here: https://github.com/groundmelon/m100_x3

I will update the readme in this repository later

**Comment by kc8goq** [comment]
Ok.  We will give this a try.     

So far we had been using robot_upstart package in ROS to launch all the drivers at power up.

Cheers

**Comment by lanyusea** [comment]
the ros pkg also suffers this problem when ssh, robot_upstart won't solve it since it is an driver layer problem instead of an application layer problem.

as I think

**Comment by kc8goq** [comment]
So far it _appears_ to be working reliably to launch the camera (to the DJI GO app) and the DJI SDK code.   We have the GuidanceNode able to run as a launch file and it's working well also.  Thanks for your hard work!

**Comment by lanyusea** [comment]
good luck!
