### ISSUE TITLE
/dev/gadget: not mounted  Error

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [dji-sdk/manifold_cam#5]
Hello,

I've been trying to run this demo to valited my setup but I've been getting the following error :

System init.......
create ivafilter success
Inside NvxLiteH264DecoderLowLatencyInitNvxLiteH264DecoderLowLatencyInit set DPB and Mjstreamingdisable host
enable device
mount: unknown filesystem type 'gadgetfs'
mount gadgetfs
Couldn't open device.
Error: init error
system exit...........
umount2: Invalid argument
umount: /dev/gadget: not mounted
All threads exit successfully !

Any idea of what is happening?

Thanks

**Comment by lanyusea** [comment]
1. are you using Manifold?
2. did you sudo?

**Comment by andre-nguyen** [comment]
1. yes
2. yes

We had the same problem with the code in Onboard-SDK-ROS

**Comment by lanyusea** [comment]
how did you connect the Manifold with Camera and NCore? could post an image for me to check?

**Comment by andre-nguyen** [comment]
Sure,

I'll let @AlexandreBorowczyk take care of that tomorrow. I'd be awkward if we swapped the cam in and cam out wires :joy_cat:

**Comment by AlexandreBorowczyk** [comment]
Hi @lanyusea,

Thanks for the quick answer, I'll get the picture you asked as soon as possible. Meanwhile, I'm quite confident than the wiring is as per : [Connecting Manifold to the Camera](https://camo.githubusercontent.com/1f739bde97447af775dc7d0623f3ae2f70c9af68/687474703a2f2f692e696d6775722e636f6d2f377149394939522e706e67). Furthermore, when powering the matrice 100, the X3 seems to execute it's initiation normally. It rotation around then point directly in front. Also when I observe the camera settings on the DJI GO app I notice that although no image is display the camera ISO setting will react if I wave my hand infront of the camera.

**Comment by lanyusea** [comment]
em.... that's quite strange and it's the first time I saw a log like this.
1. does the camera work well when it is connected to M100 directly.
2. maybe you need to update the firmware of gimbal/x3/M100 and the library?

It seems that the device has already been opened. so it failed when there is a second attempt.
I guess a reboot may solve it ... (but perhaps not

and did you guys modify the kernel before? the gadget of usb driver must be enabled if so

**Comment by lanyusea** [comment]
@AlexandreBorowczyk @andre-nguyen how is everything now?

**Comment by andre-nguyen** [comment]
I'm having trouble upgrading the firmware through the SD card + gimbal procedure.
- With version `v.1.3.1.00` I get `result: failed` in the txt file.
- I tried following a note mentioned in the release notes about flashing `Zenmuse X3 Camera Firmware v1.0.01.01` and then trying the aircraft upgrade but that file didn't start the upgrade procedure.
- I then tried `v.1.2.0.80` and now I'm getting 6 beeps followed by one long continuous one. I assume this is the error state.

**Comment by AlexandreBorowczyk** [comment]
According to dji assistant our firmware (of m100) is up to date. 

> does the camera work well when it is connected to M100 directly.

When connecting the X3 straight to the m100, everything works fine and we can get the video through DJI Go.

> and did you guys modify the kernel before

No we used the image that was already flashed on the Manifold out of the box.

**Comment by lanyusea** [comment]
@andre-nguyen 

> I then tried v.1.2.0.80 and now I'm getting 6 beeps followed by one long continuous one. I assume this is the error state.

does your drone work well know? or it keeps in b-b-b-b after poweron?

@AlexandreBorowczyk 
I asked the staffs who design Manifold, they told me the /dev/gadget is occupied so the code failed to open it again. A reboot may solve it.

**Comment by andre-nguyen** [comment]
If we leave the firmware binary in the SD card in the X3 the upgrade will fail and there will be a continuous tone heard. The last thing we tried before leaving the lab today was to remove the X3 and upgrade the m100 through  dji assistant. It says the upgrade was successful but I'm skeptical about that because DJI Go still says we are on v1.20.0.90 or something like that instead of 1.3.xx.xx

I'll see if the simple reboot works tomorrow but it seems weird it would since it has never worked even once.

**Comment by lanyusea** [comment]
@andre-nguyen

don't use the v1.0.01.01 gimbal firmware, use the v.1.3.1.00 packed firmware instead.

did it say the `fail` or `version is older than current one, abort`?
if it is `fail` you can find a detailed updating log in a hidden folder inside the SD card to check what's going on.
as I remember, the gimbal firmware will be upgraded although it failed to upgrade the controller.

**Comment by andre-nguyen** [comment]
Thanks for the tips, I was able to find the log folder. I have uploaded a video of what is happening with the upgrade procedure, hopefully you can hear the beeps despite the noise https://www.youtube.com/watch?v=bLC9M7B9U0I.

Also, I have tried the reboot method and we are still getting the error.

Below is the layout of our SD card.

```
ubuntu@tegra-ubuntu:/media/ubuntu/7B23-8823$ ls * -lahR
-rwx------ 1 ubuntu ubuntu 2.6K Jan  1  2014 MATRICE100_FW_RESULT_AB.txt
-rwx------ 1 ubuntu ubuntu  74M Apr 13 10:52 MATRICE100_FW_V01.03.01.00.bin

DCIM:
total 64K
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 .
drwx------ 1 ubuntu ubuntu 32K Dec 31  1969 ..

MISC:
total 192K
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 .
drwx------ 1 ubuntu ubuntu 32K Dec 31  1969 ..
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 IDX
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 LOG
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 THM
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 XCODE

MISC/IDX:
total 64K
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 .
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 ..

MISC/LOG:
total 160K
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 .
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 ..
-rwx------ 1 ubuntu ubuntu 19K Jan  1  2014 MATRICE100_FW_LOG_AB.txt
-rwx------ 1 ubuntu ubuntu   6 Jan  1  2014 OSMO_CAM_VERSION
-rwx------ 1 ubuntu ubuntu   7 Jan  1  2014 OSMO_FW_PROGRESS

MISC/THM:
total 64K
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 .
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 ..

MISC/XCODE:
total 64K
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 .
drwx------ 1 ubuntu ubuntu 32K Jan  1  2014 ..
```

The log files are pretty long but I'll paste below the latest entries.

In `MATRICE100_FW_RESULT_AB.txt` is below. Interestingly enough one entry says abort while the next ones say failure.

```
========== 2014.01.01 00:00:07 remo-con disconnect======
Packet: MATRICE100_FW_V01.03.01.00.bin
Result: Abort.
The firmware on the SD card is identical to or older than the current firmware on the device.

========== 2014.01.01 00:00:07 remo-con disconnect======
Packet: MATRICE100_FW_V01.03.01.00.bin
Result: Failed.
Reboot the aircraft and try to upgrade the firmware again.

========== 2014.01.01 00:00:06 remo-con disconnect======
Packet: MATRICE100_FW_V01.03.01.00.bin
Result: Failed.
Reboot the aircraft and try to upgrade the firmware again.

========== 2014.01.01 00:00:06 remo-con disconnect======
Packet: MATRICE100_FW_V01.03.01.00.bin
Result: Failed.
Reboot the aircraft and try to upgrade the firmware again.

========== 2014.01.01 00:00:06 remo-con disconnect======
Packet: MATRICE100_FW_V01.03.01.00.bin
Result: Failed.
Reboot the aircraft and try to upgrade the firmware again.

========== 2014.01.01 00:00:07 remo-con disconnect======
Packet: MATRICE100_FW_V01.03.01.00.bin
Result: Failed.
Reboot the aircraft and try to upgrade the firmware again.
```

In `MATRICE100_FW_LOG_AB.txt` we have

```
 [00006791]========== remo-con disconnect. boot(15) ============
 [00006852]Packet [C:\MATRICE100_FW_V01.03.01.00.bin] detected, card sn [0xf960d58f].
 [00006897]Packet upgrade start...

 [00006959]Packet checking...
 [00007010]Packet vlink 01.03.0100 <-> 01.02.0080.
 [00007059]Record vlink 01.03.0100 <-> 01.02.0080 (flow = 0).
 [00007107]Done.

 [00007163]Version checking[1]...
 [00007431][08 00][00] v2.14.9.42 -> v2.14.9.42
 [00007589][03 05][00] v34.1.0.10 -> v34.1.0.10
 [00007811][03 06][00] v3.1.6.103 -> v3.1.6.103
 [00007950][12 00][00] v1.12.0.0 -> v1.12.0.0
 [00008049][12 01][00] v1.12.0.0 -> v1.12.0.0
 [00008148][12 02][00] v1.12.0.0 -> v1.12.0.0
 [00008249][12 03][00] v1.12.0.0 -> v1.12.0.0
 [00011214][15 00][00] device not detected.
 [00011288][19 00][00] v1.0.8.96 -> v1.0.8.96
 [00011336][01 00][00] v2.65.5033 -> v2.65.5033
 [00011423][01 01][00] v2.65.5033 -> v2.65.5033
 [00011484][04 00][00] v1.29.0.92 -> v1.29.0.92
 [00011588][05 00][00] v3.0.6.2 -> v3.0.6.2
 [00011648][09 00][00] v3.0.0.4 -> v3.0.0.4
 [00011754][11 00][00] v3.9.0.0 -> v3.9.0.0
 [00013806]Packet upgrade failed at version checking.
```

Also with respect to DJI Go app, if we turn on the RC after the video I posted we have:
![13078135_10207813379443998_1948636746_o](https://cloud.githubusercontent.com/assets/6036318/14688890/ca6c57ac-0712-11e6-92e1-257aaf5ed82f.png)

When we reboot and go to `General Settings > About` we get:
![13062977_10156824974845483_1471912993087455868_o](https://cloud.githubusercontent.com/assets/6036318/14688929/f39e9842-0712-11e6-862f-55b944b234d3.jpg)

And if we plug in to DJI Assistant we get:
![13035657_10207807183169095_1394685000_o](https://cloud.githubusercontent.com/assets/6036318/14688940/ff00dfd8-0712-11e6-94c7-cb66fd3bddf0.png)

I suspect that this upgrade issue affects multiple users. However I am unsure if other people are unable to get the X3 video data from the manifold.

**Comment by lanyusea** [comment]
@andre-nguyen 
1. well, currently, I have no idea about the upgrade fail, I think there is a technical issue and suggest you contact dev@dji.com or support@dji.com for help from after-sale team.
2. the DJI GO says the firmware is 1.2.0.90+, where "+" means it is higher than 1.2.0.90. It should show the correct version after your DJI GO connected to Internet and fetching the latest version table.
3. em... this is the first case we met related to /dev/gadget cannot be mounted. The Manifold team told me /dev/gadget is a usb driver, which should be set to free and be able to mount again after a reboot. And the final conclusion is: reburn the system by official image may solve it, but unsure.

**Comment by andre-nguyen** [comment]
Thanks for the tips and suggestions, I wanted to flash the official image but it seems this page: https://developer.dji.com/en/manifold/downloads/ doesn't exist anymore, do you know where I can get the official image?

edit: nvm found it

**Comment by andre-nguyen** [comment]
@lanyusea It worked!!
All I did was flash the Manifold with the system image downloaded from DJI and now it's working. You can close this issue.

I wonder if maybe a system update of some sort broke something. If that happened I'll open a new issue so we can further investigate.
